### ISSUE TITLE
RFC: Rename to `conda-pypi`?

### ISSUE THREAD

**Issue by jaimergp** [jaimergp/conda-pip#15]
I'm not sure `conda-pip` is the right name for the project and package. We are implementing tool agnostic behavior with EXTERNALLY-MANAGED and while we do have the `conda pip` _subcommand_, chances are we will also have `conda uv` in the future (or similar). Hence I think `conda-pypi` might be a better name for the _project_, which happens to implement the `pip` subcommand for now. 

Thoughts? This a simple change to do now but it might get a bit more complicated later when things are packaged and folks start adding this to requirements, etc.

**Comment by jezdez** [comment]
I would rather call it `conda-python` since PyPI is the hosting service, not the purpose of the plugin.

**Comment by dharhas** [comment]
> conda-python is too broad imo

agreed. for better or for worse, `conda-pypi` is the most descriptive, least confusing name.

Other ideas `conda-interop`, `conda-compat`, `conda-resolve` or something completely unrelated i.e `chimera`

**Comment by jaimergp** [comment]
`conda-pypi-compat`?

**Comment by jaimergp** [comment]
One more argument / precedent for `pypi`:

- It has been used as a ["channel" identifier](https://github.com/conda/conda/blob/be5adf514550260952f20a807748f7f3ae297f10/conda/gateways/disk/read.py#L259) in the conda ecosystem.

**Comment by jezdez** [comment]
You've changed my mind, conda-pypi is the better term, as it goes well with the idea of making conda aware of additional 3rd party packaging ecosystem (independent of its own). This would bode well for supporting others long-term (e.g. R, npm, etc)
